### PR TITLE
MGDCTRS-1556: fix: Reverted the changes to fix

### PR DESCRIPTION
**Pull request by indraraj**

### CODE REVIEW

**Comment by indraraj** [comment]
We may have to figure out a way to add the e2e test cases for the flows with federated modules(DBZ). Because those are the most probable ones to be overlooked while refactoring or making new changes.

**Comment by gashcrumb** [comment]
Yep, I think that's a really good idea.  It's not obvious from the code or this PR what the difference is between the configuration formats.  It may also be worthwhile thinking about how we could layer/compose the configuration components better to try and remove all of these various checks of the format of the config object.  Could we have a debezium specific config tab/component vs a Camel specific config tab/component and separate the concerns a bit?  I think each component that has to figure this out one way or another as part of it's rendering is already probably dealing with too much.

**Comment by gashcrumb** [comment]
Honestly probably this PR would be a good time to introduce such an integration test if this is fixing a regression.

**Review by gashcrumb — APPROVED** [review]
:+1: works for me!  If you want to merge this now and add a test later that's fine.

**Review by uidoyen — APPROVED** [review]
LGTM :+1:

**Comment by indraraj** [comment]
created the flow up Jira for adding the integration test cases for the DBZ flows https://issues.redhat.com/browse/MGDCTRS-1572

**Pull request merged**
