### PR TITLE
MGDCTRS-772 feat: server-side filtering/ordering

### PR DESCRIPTION
**Pull request by gashcrumb**
This change updates the pagination utility classes to add support for
orderBy and aligns the filtering support to better match the API.  This
change also updates the pagination usage a little bit across the
toolbars in the application.  Finally this change also brings back the
search filter on the connectors instance list.  Further work is needed
to add sorting controls as well as additional filter categories for the
connectors instance list search.

### CODE REVIEW

**Comment by gashcrumb** [comment]
I opted to do some renaming as part of this to better align with the API terms so it kinda made this effort a bit bigger, sorry about that!

**Comment by indraraj** [comment]
Hey @gashcrumb while testing it looks like connector type API search does not support the partial search, I think it should be supported to make the search functionality helpful to the users, and for the case when I tried to put the exact same connector type (like "Amazon Kinesis sink") it's giving me 404
image

**Comment by gashcrumb** [comment]
@indraraj it's the spaces in the search query.   Another issue with the server-side search is that it's case sensitive.  I tried putting the query in quotes already before sending it but that didn't seem to help.  Anyways, I have an issue open already for the case sensitive search, let me mention the space issue on there too.

**Comment by gashcrumb** [comment]
@indraraj hm, I didn't test enough using quotes the first time :smile:.  I'll push an update in a few.

**Comment by gashcrumb** [comment]
@indraraj should be sorted whenever you're ready, thanks!

**Review by uidoyen — CHANGES_REQUESTED** [review]
@gashcrumb  I tried to search using **debezium** keyword and I got `No results found` but when I search **Debezium** I get the result. Can we make it case-insensitive?
Screenshot from 2022-06-30 20-51-54

Screenshot from 2022-06-30 20-57-57

**Comment by gashcrumb** [comment]
@uidoyen yeah, the server-side search is case sensitive but needs to be adjusted at the backend afaik, I've https://issues.redhat.com/browse/MGDCTRS-1128 open for that.

**Review by uidoyen — APPROVED** [review]

**Review by indraraj — APPROVED** [review]

**Pull request merged**
