### PR TITLE
MGDCTRS-1773 feat: better connector error display

### PR DESCRIPTION
**Pull request by gashcrumb**
This commit adopts the new inline error alert components into the app in both the connector drawer and the connector overview page.  This change also promotes these components from the ProofOfConcepts directory and renames the components to closer match their usage.  Also this change contains a re-alphabetize of the locales file.

Connector instances drawer:
Screenshot from 2023-01-18 14-05-53

Overview page:
Screenshot from 2023-01-18 14-06-31

### CODE REVIEW

**Comment by gashcrumb** [comment]
@mmuzikar if you had any tests checking for the error message on a connector...

**Comment by gashcrumb** [comment]
@nding-anges @aprilma419 this is an updated component

**Comment by gashcrumb** [comment]
Rebased and fixed the commit message :smile:

**Comment by indraraj** [comment]
It looks like we already get the "**Error:** " appended to the error msg coming from the backend, causing us to duplicate it on the UI side. Maybe we can check with the backend team and if agreed we can remove it from the UI side

**Review by indraraj — APPROVED** [review]
Tested Locally and looks good 👍 just one comment above.

**Comment by gashcrumb** [comment]
> It looks like we already get the "Error: " appended to the error msg coming from the backend, causing us to duplicate it on the UI side. Maybe we can check with the backend team and if agreed we can remove it from the UI side

Yeah, I had a question on this in the Jira too if I was interpreting the design to literally :smile:.  I opted to leave it as-is and we can adjust the locale string as needed.

**Pull request merged**
