### PR TITLE
MGDCTRS-729: fix: use the default value in error handling step

### PR DESCRIPTION
**Pull request by indraraj**
Closes the issue 

https://issues.redhat.com/browse/MGDCTRS-729

### CODE REVIEW

**Comment by indraraj** [comment]
Merge only when https://github.com/bf2fc6cc711aee1a0c2a/cos-fleet-catalog-camel/pull/164 is deployed to the staging

**Comment by gashcrumb** [comment]
I gave a quick test of this here it doesn't appear to fix the issue, does this rely on an API change?

**Comment by indraraj** [comment]
> Just to check I'm testing the right thing, it's for this page, right?
> 
> image



> I gave a quick test of this here, however it doesn't appear to fix the issue, does this rely on an API change?

Yes, I see that backend changes are deployed to Dev cluster. you can test there.

**Comment by indraraj** [comment]
Sry my bad I didn't mention the details covered by the PR. In this PR I covered the Wizard Error handler step by adding the default value there
image

Anyway I guess I will update the PR to cover the Edit step also

**Comment by indraraj** [comment]
@gashcrumb updated the Jira and the PR to handle the error handling step in the edit flow.

**Review by gashcrumb — APPROVED** [review]
:+1: awesome, thanks for letting me know, totally missed that.  LGTM!

**Comment by indraraj** [comment]
Backend changes need to be deployed first.

**Pull request merged**
