### PR TITLE
MGDCTRS-772 feat: switch to case insensitive filter and add sortable columns

### PR DESCRIPTION
**Pull request by gashcrumb**
These changes:

- updates the SQL query to use a case insensitive search
- Refactors the table to use TableView from app-services-components-ui
	- This required aligning a few versions
- Makes the column headers clickable to change the table sort ordering

image

Note that this will currently only work in dev.

### CODE REVIEW

**Comment by gashcrumb** [comment]
Found this while fixing merge conflicts, wonder @riccardo-forina have you spotted this one: 

image

**Comment by gashcrumb** [comment]
Hmm, another issue to look into, when resizing the page to a narrow view there's no pagination arrows:

image

**Comment by gashcrumb** [comment]
Created https://github.com/redhat-developer/app-services-ui-components/pull/506 for the pagination

**Comment by gashcrumb** [comment]
The other issue with the actions popup probably needs to be addressed in patternfly, when I adjust the example to use a scrolling container I get the same:

image

**Comment by gashcrumb** [comment]
I don't know if this is an improvement or not, it's possible to attach the underlying DropDown to another element, but even attaching it to `document.body`:

image

This is done by passing:

`rowData={{ actionProps: { menuAppendTo: document.body } }}`

to `ActionsColumn`.  I tried also passing the element that's a parent of the TableView, maybe though it's the card that's overflowing.

**Review by indraraj — APPROVED** [review]
LGTM :+1:

**Comment by riccardo-forina** [comment]
@dlabaj FYI some of the issues with the table are listed here

**Comment by indraraj** [comment]
@gashcrumb is more work needed to complete this? (apart from conflicts)

**Comment by gashcrumb** [comment]
@indraraj this should be good to go assuming the checks pass :smile:

**Pull request merged**
