### PR TITLE
MGDCTRS-699 chore: refactor the i18n json

### PR DESCRIPTION
**Pull request by gashcrumb**
This PR updates the i18n json file to use a consistent camel case
convention for i18n keys.  It also sorts the json by key and removes a
number of duplicate entries.  This also updates most of the strings as
requested in MGDCTRS-699 that are in the i18n configuration, follow up
commits will be needed for components that haven't yet been localized.
Given all the changes this commit also removes the Italian translation,
we can create a new one once things are more finalized.

@indraraj @uidoyen apologies for such a massive PR!  Hopefully camel case for i18n keys works for you, I'd suggest we try and maintain this format from this point on, it'll really make our lives easier.

### CODE REVIEW

**Comment by gashcrumb** [comment]
Rebased

**Comment by gashcrumb** [comment]
Spotted a bug too:

image

lemme fix that.

**Comment by gashcrumb** [comment]
Ok, all set to look at again whenever :-)

**Review by indraraj — APPROVED** [review]
Tested locally, looks good.

**Comment by indraraj** [comment]
@gashcrumb this section https://docs.google.com/document/d/1m-LorqWCPjGFc-W4RM5BqWl5JC3cYtZ6bnlCpLecnc0/edit#heading=h.nsdoaklq9oa3 still needs to be implemented. I have created a subtask [MGDCTRS-774](https://issues.redhat.com/browse/MGDCTRS-774) Within MGDCTRS-699 I can work on this next week.

**Comment by gashcrumb** [comment]
Awesome, thanks!  I spotted one other bug and have now rebased it again.

**Comment by gashcrumb** [comment]
> @gashcrumb this section https://docs.google.com/document/d/1m-LorqWCPjGFc-W4RM5BqWl5JC3cYtZ6bnlCpLecnc0/edit#heading=h.nsdoaklq9oa3 still needs to be implemented. I have created a subtask [MGDCTRS-774](https://issues.redhat.com/browse/MGDCTRS-774) Within MGDCTRS-699 I can work on this next week.

Ah hadn't even spotted this before replying. That's fantastic, appreciate it!

**Pull request merged**
