### PR TITLE
MGDCTRS-1419: feat: disable the action items if connector enters to deleted desired state

### PR DESCRIPTION
**Pull request by indraraj**
Closes https://issues.redhat.com/browse/MGDCTRS-1419 https://issues.redhat.com/browse/MGDCTRS-1447

### CODE REVIEW

**Review by uidoyen — APPROVED** [review]
LGTM :+1:

**Review by gashcrumb — APPROVED** [review]
:+1:

**Comment by indraraj** [comment]
added the test cases and fixed connector type card stories.

**Review by uidoyen — APPROVED** [review]
:+1:

**Pull request merged**
