### PR TITLE
MGDCTRS-1419: fix: disable clickable connector name for deleted desired_state

### PR DESCRIPTION
**Pull request by indraraj**
Closes https://issues.redhat.com/browse/MGDCTRS-1419

Screenshot
image

### CODE REVIEW

**Comment by gashcrumb** [comment]
@indraraj adding a check to the connectors instances integration test would be good if you've time, it's a subtle behavior that's easy to miss during a refactor.

**Comment by indraraj** [comment]
> @indraraj adding a check to the connectors instances integration test would be good if you've time, it's a subtle behavior that's easy to miss during a refactor.

Sure 👍 I will update it

**Review by uidoyen — APPROVED** [review]
LGTM :+1:

**Comment by gashcrumb** [comment]
I can add that check to my PR there for the delete modal, not a problem :-).

**Pull request merged**
