### PR TITLE
chore: get react refresh working

### PR DESCRIPTION
**Pull request by gashcrumb**
This change adds the necessary configuration for react refresh and
ts-loader.  It also removes the extra entrypoint that was causing two
client side instances of the hot module loading code to run.  This
ensures that code changes will be reloaded in the browser properly.
Also this commit favors the error overlay from react refresh over the
built in one from webpack dev server.

This effort started as me manually bumping dependencies to help out renovate until I realized that while we had the necessary dependencies installed they weren't configured.

### CODE REVIEW

**Comment by gashcrumb** [comment]
I'm not satisfied this works yet in federated mode properly, will need to look into this further tomorrow.

**Comment by gashcrumb** [comment]
Federated mode isn't broken with this, however the dev experience won't be as good as standalone.  There's some content security policy configuration that needs to be figured out to make that happen and it likely needs to happen in app-services-ui.  I'll look at that next but I think this is in a good state for a second pair of eyes to give it a try.

**Review by indraraj — APPROVED** [review]
Tested Locally, Looks good

**Comment by gashcrumb** [comment]
Awesome, thanks!

**Pull request merged**
